version: "3.8"

services:
#DATABASE IMAGE FROM DOCKER
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - expo-network

#BACKEND
  backend:
    image: farhan249/expo-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
    - mongodb
    environment:
      - "MONGO_URI=mongodb://mongodb:27017/expodb"
    networks:
      - expo-network
  
  #FRONTEND
  fronted:
    image: farhan249/expo-frontend:latest
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - expo-network


volumes:
  mongo-data:


networks:
  expo-network:
    driver: bridge

